system:
    default:
        fielddefinition_settings_templates:
            -
                template: "EzExtraMediaBundle::fielddefinition_settings.html.twig"
        fielddefinition_edit_templates:
            -
                template: "EzExtraMediaBundle::field_types.html.twig"
        field_templates:
            -
                template: "EzExtraMediaBundle::content_fields.html.twig"

