parameters:
    ezpublish.fieldType.ezextramedia.converter.class: TheCocktail\EzMediaBundle\Persistence\Content\FieldValue\Converter\EzMediaConverter

services:
    ezpublish.fieldType.ezextramedia.converter:
        class: "%ezpublish.fieldType.ezextramedia.converter.class%"
        tags:
            - {name: ezpublish.storageEngine.legacy.converter, alias: ezextramedia, lazy: true, callback: '::create'}

