parameters:
    ezpublish.fieldType.indexable.ezextramedia.class: TheCocktail\EzExtraMediaBundle\FieldType\EzExtraMedia\SearchField

services:
    ezpublish.fieldType.indexable.ezextramedia:
        class: "%ezpublish.fieldType.indexable.ezextramedia.class%"
        tags:
            - {name: ezpublish.fieldType.indexable, alias: ezextramedia}
