system:
    default:
        yui:
            modules:
                ez-rawcontentview:
                    requires:
                        - 'ezextramedia-view'
                ez-contenteditformview:
                    requires:
                        - 'ezextramedia-editview'
                ezextramedia-view:
                    requires: ['ez-fieldview', 'ezextramediaview-ez-template']
                    path: "%ezextramediafieldtype.public_dir%/js/views/fields/ezextramedia-view.js"
                ezextramedia-editview:
                    requires: ['ez-fieldeditview', 'event-valuechange', 'ezextramediaeditview-ez-template']
                    path: "%ezextramediafieldtype.public_dir%/js/views/fields/ezextramedia-editview.js"
                ezextramediaview-ez-template:
                    type: 'template'
                    path: "%ezextramediafieldtype.public_dir%/templates/fields/view/ezextramedia.hbt"
                ezextramediaeditview-ez-template:
                    type: 'template'
                    path: "%ezextramediafieldtype.public_dir%/templates/fields/edit/ezextramedia.hbt"




