system:
    default:
        fielddefinition_settings_templates:
            -
                template: "EzMediaBundle::fielddefinition_settings.html.twig"
        fielddefinition_edit_templates:
            -
                template: "EzMediaBundle::field_types.html.twig"
        field_templates:
            -
                template: "EzMediaBundle::content_fields.html.twig"

